export const Provinces = [
  {
    id: "1",
    name: "Koshi Pradesh",
    districts: [
      {
        id: "1",
        name: "Bhojpur",
        municipalities: [
          { id: "94", name: "Bhojpur", type: "municipality" },
          { id: "95", name: "Shadananda", type: "municipality" },
          { id: "96", name: "Aamchowk", type: "rural-municipality" },
          { id: "97", name: "Arun", type: "rural-municipality" },
          { id: "98", name: "Hatuwagadhi", type: "rural-municipality" },
          { id: "99", name: "Pauwadungma", type: "rural-municipality" },
          { id: "100", name: "Ramprasad Rai", type: "rural-municipality" },
          { id: "101", name: "Salpasilichho", type: "rural-municipality" },
          { id: "102", name: "Tyamkemaiyung", type: "rural-municipality" },
        ],
      },
      {
        id: "2",
        name: "Dhankuta",
        municipalities: [
          { name: "Dhankuta", type: "municipality" },
          { name: "Mahalaxmi", type: "municipality" },
          { name: "Pakhribas", type: "municipality" },
          { name: "Chaubise", type: "rural-municipality" },
          { name: "Chhathar Jorpati", type: "rural-municipality" },
          { name: "Khalsa Chhintang Shahidbhumi", type: "rural-municipality" },
          { name: "Sangurigadhi", type: "rural-municipality" },
        ],
      },
      {
        id: "3",
        name: "Ilam",
        municipalities: [
          { name: "Deumai", type: "municipality" },
          { name: "Ilam", type: "municipality" },
          { name: "Mai", type: "municipality" },
          { name: "Suryodaya", type: "municipality" },
          { name: "Chulachuli", type: "rural-municipality" },
          { name: "Fakphokthum", type: "rural-municipality" },
          { name: "Maijogmai", type: "rural-municipality" },
          { name: "Mangsebung", type: "rural-municipality" },
          { name: "Rong", type: "rural-municipality" },
          { name: "Sandakpur", type: "rural-municipality" },
        ],
      },
      {
        id: "4",
        name: "Jhapa",
        municipalities: [
          { name: "Arjundhara", type: "municipality" },
          { name: "Bhadrapur", type: "municipality" },
          { name: "Birtamod", type: "municipality" },
          { name: "Damak", type: "municipality" },
          { name: "Gauradhaha", type: "municipality" },
          { name: "Kankai", type: "municipality" },
          { name: "Mechinagar", type: "municipality" },
          { name: "Shivasataxi", type: "municipality" },
          { name: "Barhadashi", type: "rural-municipality" },
          { name: "Buddhashanti", type: "rural-municipality" },
          { name: "Gauriganj", type: "rural-municipality" },
          { name: "Haldibari", type: "rural-municipality" },
          { name: "Jhapa", type: "rural-municipality" },
          { name: "Kachankawal", type: "rural-municipality" },
          { name: "Kamal", type: "rural-municipality" },
        ],
      },
      {
        id: "5",
        name: "Khotang",
        municipalities: [
          { name: "Halesi Tuwachung", type: "municipality" },
          { name: "Rupakot Majhuwagadhi", type: "municipality" },
          { name: "Ainselukhark", type: "rural-municipality" },
          { name: "Barahapokhari", type: "rural-municipality" },
          { name: "Diprung", type: "rural-municipality" },
          { name: "Jantedhunga", type: "rural-municipality" },
          { name: "Kepilasagadhi", type: "rural-municipality" },
          { name: "Khotehang", type: "rural-municipality" },
          { name: "Lamidanda", type: "rural-municipality" },
          { name: "Sakela", type: "rural-municipality" },
        ],
      },
      {
        id: "6",
        name: "Morang",
        municipalities: [
          { name: "Biratnagar", type: "metropolis" },
          { name: "Belbari", type: "municipality" },
          { name: "Letang", type: "municipality" },
          { name: "Patahri Shanishchare", type: "municipality" },
          { name: "Rangeli", type: "municipality" },
          { name: "Ratuwamai", type: "municipality" },
          { name: "Sundarharaicha", type: "municipality" },
          { name: "Sunwarshi", type: "municipality" },
          { name: "Uralabari", type: "municipality" },
          { name: "Budhiganga", type: "rural-municipality" },
          { name: "Dhanpalthan", type: "rural-municipality" },
          { name: "Gramthan", type: "rural-municipality" },
          { name: "Jahada", type: "rural-municipality" },
          { name: "Kanepokhari", type: "rural-municipality" },
          { name: "Katahari", type: "rural-municipality" },
          { name: "Kerabari", type: "rural-municipality" },
          { name: "Miklajung", type: "rural-municipality" },
        ],
      },
      {
        id: "7",
        name: "Okhaldhunga",
        municipalities: [
          { name: "Siddhicharan", type: "municipality" },
          { name: "Champadevi", type: "rural-municipality" },
          { name: "Chisankhugadhi", type: "rural-municipality" },
          { name: "Khijidemba", type: "rural-municipality" },
          { name: "Likhu", type: "rural-municipality" },
          { name: "Manebhanjyang", type: "rural-municipality" },
          { name: "Molung", type: "rural-municipality" },
          { name: "Sunkoshi", type: "rural-municipality" },
        ],
      },
      {
        id: "8",
        name: "Panchthar",
        municipalities: [
          { name: "Phidim", type: "municipality" },
          { name: "Falelung", type: "rural-municipality" },
          { name: "Falgunanda", type: "rural-municipality" },
          { name: "Hilihang", type: "rural-municipality" },
          { name: "Kummayak", type: "rural-municipality" },
          { name: "Miklajung", type: "rural-municipality" },
          { name: "Tumbewa", type: "rural-municipality" },
          { name: "Yangwarak", type: "rural-municipality" },
        ],
      },
      {
        id: "9",
        name: "Sankhuwasabha",
        municipalities: [
          { name: "Chainpur", type: "municipality" },
          { name: "Dharmadevi", type: "municipality" },
          { name: "Khandbari", type: "municipality" },
          { name: "Madi", type: "municipality" },
          { name: "Panchakhapan", type: "municipality" },
          { name: "Bhotkhola", type: "rural-municipality" },
          { name: "Chichila", type: "rural-municipality" },
          { name: "Makalu", type: "rural-municipality" },
          { name: "Sabhapokhari", type: "rural-municipality" },
          { name: "Silichong", type: "rural-municipality" },
        ],
      },
      {
        id: "10",
        name: "Solukhumbu",
        municipalities: [
          { name: "Solududhakunda", type: "municipality" },
          { name: "Dudhkaushika", type: "rural-municipality" },
          { name: "Dudhkoshi", type: "rural-municipality" },
          { name: "Khumbu Pasanglahmu", type: "rural-municipality" },
          { name: "Likhupike", type: "rural-municipality" },
          { name: "Mahakulung", type: "rural-municipality" },
          { name: "Nechasalyan", type: "rural-municipality" },
          { name: "Sotang", type: "rural-municipality" },
        ],
      },
      {
        id: "11",
        name: "Sunsari",
        municipalities: [
          { name: "Dharan", type: "sub-metropolis" },
          { name: "Itahari", type: "sub-metropolis" },
          { name: "Barah", type: "municipality" },
          { name: "Duhabi", type: "municipality" },
          { name: "Inarwa", type: "municipality" },
          { name: "Ramdhuni", type: "municipality" },
          { name: "Barju", type: "rural-municipality" },
          { name: "Bhokraha", type: "rural-municipality" },
          { name: "Dewanganj", type: "rural-municipality" },
          { name: "Gadhi", type: "rural-municipality" },
          { name: "Harinagara", type: "rural-municipality" },
          { name: "Koshi", type: "rural-municipality" },
        ],
      },
      {
        id: "12",
        name: "Taplejung",
        municipalities: [
          { name: "Phungling", type: "municipality" },
          { name: "Aathrai Tribeni", type: "rural-municipality" },
          { name: "Maiwakhola", type: "rural-municipality" },
          { name: "Meringden", type: "rural-municipality" },
          { name: "Mikwakhola", type: "rural-municipality" },
          { name: "Phaktanglung", type: "rural-municipality" },
          { name: "Sidingba", type: "rural-municipality" },
          { name: "Sirijangha", type: "rural-municipality" },
          { name: "Yangwarak", type: "rural-municipality" },
        ],
      },
      {
        id: "13",
        name: "Terhathum",
        municipalities: [
          { name: "Laligurans", type: "municipality" },
          { name: "Myanglung", type: "municipality" },
          { name: "Aathrai", type: "rural-municipality" },
          { name: "Chhathar", type: "rural-municipality" },
          { name: "Menchayam", type: "rural-municipality" },
          { name: "Phedap", type: "rural-municipality" },
        ],
      },
      {
        id: "14",
        name: "Udayapur",
        municipalities: [
          { name: "Belaka", type: "municipality" },
          { name: "Chaudandigadhi", type: "municipality" },
          { name: "Katari", type: "municipality" },
          { name: "Triyuga", type: "municipality" },
          { name: "Rautamai", type: "rural-municipality" },
          { name: "Sunkoshi", type: "rural-municipality" },
          { name: "Tapli", type: "rural-municipality" },
          { name: "Udayapurgadhi", type: "rural-municipality" },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Madhesh Pradesh",
    districts: [
      {
        id: "15",
        name: "Bara",
        municipalities: [
          { id: "66", name: "Jitpur Simara", type: "sub-metropolis" },
          { id: "67", name: "Kalaiya", type: "sub-metropolis" },
          { id: "68", name: "Kolhabi", type: "municipality" },
          { id: "69", name: "Mahagadhimai", type: "municipality" },
          { id: "70", name: "Nijgadh", type: "municipality" },
          { id: "71", name: "Pacharauta", type: "municipality" },
          { id: "72", name: "Simroungadh", type: "municipality" },
          { id: "73", name: "Adarsh Kotwal", type: "rural-municipality" },
          { id: "74", name: "Baragadhi", type: "rural-municipality" },
          { id: "75", name: "Bishrampur", type: "rural-municipality" },
          { id: "76", name: "Devtal", type: "rural-municipality" },
          { id: "77", name: "Karaiyamai", type: "rural-municipality" },
          { id: "78", name: "Parwanipur", type: "rural-municipality" },
          { id: "79", name: "Pheta", type: "rural-municipality" },
          { id: "80", name: "Prasauni", type: "rural-municipality" },
          { id: "81", name: "Suwarna", type: "rural-municipality" },
        ],
      },
      { id: "16", name: "Parsa" },
      {
        id: "17",
        name: "Dhanusa",
        municipalities: [
          { name: "Janakpur", type: "sub-metropolis" },
          { name: "Bidehi", type: "municipality" },
          { name: "Chhireshwornath", type: "municipality" },
          { name: "Dhanusadham", type: "municipality" },
          { name: "Ganeshman Charnath", type: "municipality" },
          { name: "Hansapur", type: "municipality" },
          { name: "Kamala", type: "municipality" },
          { name: "Mithila", type: "municipality" },
          { name: "Mithila Bihari", type: "municipality" },
          { name: "Nagarain", type: "municipality" },
          { name: "Sabaila", type: "municipality" },
          { name: "Sahidnagar", type: "municipality" },
          { name: "Aurahi", type: "rural-municipality" },
          { name: "Bateshwor", type: "rural-municipality" },
          { name: "Dhanauji", type: "rural-municipality" },
          { name: "Janaknandini", type: "rural-municipality" },
          { name: "Lakshminiya", type: "rural-municipality" },
          { name: "Mithila Bihari", type: "rural-municipality" },
          { name: "Mukhiyapatti Musaharniya", type: "rural-municipality" },
        ],
      },
      {
        id: "18",
        name: "Mahottari",
        municipalities: [
          { name: "Aurahi", type: "municipality" },
          { name: "Balwa", type: "municipality" },
          { name: "Bardibas", type: "municipality" },
          { name: "Bhangaha", type: "municipality" },
          { name: "Gaushala", type: "municipality" },
          { name: "Jaleswar", type: "municipality" },
          { name: "Loharpatti", type: "municipality" },
          { name: "Manra Sisawa", type: "municipality" },
          { name: "Matihani", type: "municipality" },
          { name: "Ramgopalpur", type: "municipality" },
          { name: "Ekdanra", type: "rural-municipality" },
          { name: "Mahottari", type: "rural-municipality" },
          { name: "Pipra", type: "rural-municipality" },
          { name: "Samsi", type: "rural-municipality" },
          { name: "Sonama", type: "rural-municipality" },
        ],
      },
      {
        id: "19",
        name: "Rautahat",
        municipalities: [
          { name: "Baudhimai", type: "municipality" },
          { name: "Brindaban", type: "municipality" },
          { name: "Chandrapur", type: "municipality" },
          { name: "Devahi Gonahi", type: "municipality" },
          { name: "Gadhimai", type: "municipality" },
          { name: "Garuda", type: "municipality" },
          { name: "Gaur", type: "municipality" },
          { name: "Gujara", type: "municipality" },
          { name: "Ishanath", type: "municipality" },
          { name: "Katahariya", type: "municipality" },
          { name: "Madav Narayan", type: "municipality" },
          { name: "Maulapur", type: "municipality" },
          { name: "Paroha", type: "municipality" },
          { name: "Phatuwa Bijayapur", type: "municipality" },
          { name: "Rajdevi", type: "municipality" },
          { name: "Rajpur", type: "municipality" },
          { name: "Durga Bhagawati", type: "rural-municipality" },
          { name: "Yamunamai", type: "rural-municipality" },
        ],
      },
      {
        id: "20",
        name: "Saptari",
        municipalities: [
          { name: "Bodebarsaien", type: "municipality" },
          { name: "Dakneshwori", type: "municipality" },
          { name: "Hanumannagar Kankalani", type: "municipality" },
          { name: "Kanchanrup", type: "municipality" },
          { name: "Khadak", type: "municipality" },
          { name: "Rajbiraj", type: "municipality" },
          { name: "Saptakoshi", type: "municipality" },
          { name: "Shambhunath", type: "municipality" },
          { name: "Surunga", type: "municipality" },
          { name: "Agnisair Krishnasavaran", type: "rural-municipality" },
          { name: "Belhi Chapena", type: "rural-municipality" },
          { name: "Bishnupur", type: "rural-municipality" },
          { name: "Chhinnamasta", type: "rural-municipality" },
          { name: "Mahadeva", type: "rural-municipality" },
          { name: "Rupani", type: "rural-municipality" },
          { name: "Tilathi Koiladi", type: "rural-municipality" },
          { name: "Tirahut", type: "rural-municipality" },
          { name: "Walan Bihul", type: "rural-municipality" },
        ],
      },
      {
        id: "21",
        name: "Sarlahi",
        municipalities: [
          { name: "Bagmati", type: "municipality" },
          { name: "Balara", type: "municipality" },
          { name: "Barahathawa", type: "municipality" },
          { name: "Godaita", type: "municipality" },
          { name: "Haripur", type: "municipality" },
          { name: "Haripurwa", type: "municipality" },
          { name: "Hariwan", type: "municipality" },
          { name: "Ishworpur", type: "municipality" },
          { name: "Kabilasi", type: "municipality" },
          { name: "Lalbandi", type: "municipality" },
          { name: "Malangawa", type: "municipality" },
          { name: "Basbariya", type: "rural-municipality" },
          { name: "Bishnu", type: "rural-municipality" },
          { name: "Brahmapuri", type: "rural-municipality" },
          { name: "Chakraghatta", type: "rural-municipality" },
          { name: "Chandranagar", type: "rural-municipality" },
          { name: "Dhankaul", type: "rural-municipality" },
          { name: "Kaudena", type: "rural-municipality" },
          {
            name: "Parsa",
            type: "rural-municipality",
            municipalities: [
              { name: "Birgunj", type: "metropolis" },
              { name: "Bahudaramai", type: "municipality" },
              { name: "Parsagadi", type: "municipality" },
              { name: "Pokhariya", type: "municipality" },
              { name: "Bindabasini", type: "rural-municipality" },
              { name: "Chhipaharmai", type: "rural-municipality" },
              { name: "Dhobini", type: "rural-municipality" },
              { name: "Jagarnathpur", type: "rural-municipality" },
              { name: "Jira Bhawani", type: "rural-municipality" },
              { name: "Kalikamai", type: "rural-municipality" },
              { name: "Pakahamainpur", type: "rural-municipality" },
              { name: "Paterwasugauli", type: "rural-municipality" },
              { name: "Sakhuwa Prasauni", type: "rural-municipality" },
              { name: "Thori", type: "rural-municipality" },
            ],
          },
          { name: "Ramnagar", type: "rural-municipality" },
        ],
      },
      {
        id: "22",
        name: "Siraha",
        municipalities: [
          { name: "Dhangadhimai", type: "municipality" },
          { name: "Golbazar", type: "municipality" },
          { name: "Kalyanpur", type: "municipality" },
          { name: "Karjanha", type: "municipality" },
          { name: "Lahan", type: "municipality" },
          { name: "Mirchaiya", type: "municipality" },
          { name: "Siraha", type: "municipality" },
          { name: "Sukhipur", type: "municipality" },
          { name: "Arnama", type: "rural-municipality" },
          { name: "Aurahi", type: "rural-municipality" },
          { name: "Bariyarpatti", type: "rural-municipality" },
          { name: "Bhagawanpur", type: "rural-municipality" },
          { name: "Bishnupur", type: "rural-municipality" },
          { name: "Laxmipur patari", type: "rural-municipality" },
          { name: "Naraha", type: "rural-municipality" },
          { name: "Navarajpur", type: "rural-municipality" },
          { name: "Sakhuwanankarkatti", type: "rural-municipality" },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Bagmati Pradesh",
    districts: [
      {
        id: "23",
        name: "Bhaktapur",
        municipalities: [
          { id: "90", name: "Bhaktapur", type: "municipality" },
          { id: "91", name: "Changunarayan", type: "municipality" },
          { id: "92", name: "Madhyapur Thimi", type: "municipality" },
          { id: "93", name: "Suryabinayak", type: "municipality" },
        ],
      },
      {
        id: "24",
        name: "Chitwan",
        municipalities: [
          { id: "103", name: "Bharatpur", type: "metropolis" },
          { id: "104", name: "Kalika", type: "municipality" },
          { id: "105", name: "Khairahani", type: "municipality" },
          { id: "106", name: "Madi", type: "municipality" },
          { id: "107", name: "Rapti", type: "municipality" },
          { id: "108", name: "Ratnangar", type: "municipality" },
          { id: "109", name: "Ichchhyakamana", type: "rural-municipality" },
        ],
      },
      {
        id: "25",
        name: "Dhading",
        municipalities: [
          { name: "Dhunibesi", type: "municipality" },
          { name: "Nilakantha", type: "municipality" },
          { name: "Benighat Rorang", type: "rural-municipality" },
          { name: "Gajuri", type: "rural-municipality" },
          { name: "Galchi", type: "rural-municipality" },
          { name: "Gangajamuna", type: "rural-municipality" },
          { name: "Jwalamukhi", type: "rural-municipality" },
          { name: "Khaniyabash", type: "rural-municipality" },
          { name: "Netrawati", type: "rural-municipality" },
          { name: "Rubi Valley", type: "rural-municipality" },
          { name: "Siddhalek", type: "rural-municipality" },
          { name: "Thakre", type: "rural-municipality" },
          { name: "Tripurasundari", type: "rural-municipality" },
        ],
      },
      {
        id: "26",
        name: "Dolakha",
        municipalities: [
          { name: "Bhimeshwor", type: "municipality" },
          { name: "Jiri", type: "municipality" },
          { name: "Baiteshwor", type: "rural-municipality" },
          { name: "Bigu", type: "rural-municipality" },
          { name: "Gaurishankar", type: "rural-municipality" },
          { name: "Kalinchok", type: "rural-municipality" },
          { name: "Melung", type: "rural-municipality" },
          { name: "Sailung", type: "rural-municipality" },
          { name: "Tamakoshi", type: "rural-municipality" },
        ],
      },
      {
        id: "27",
        name: "Kathmandu",
        metropolises: [{ name: "Kathmandu", type: "metropolis" }],
        municipalities: [
          { name: "Budhanilakantha", type: "municipality" },
          { name: "Chandragiri", type: "municipality" },
          { name: "Dakshinkali", type: "municipality" },
          { name: "Gokarneshwor", type: "municipality" },
          { name: "Kageshwori Manahara", type: "municipality" },
          { name: "Kirtipur", type: "municipality" },
          { name: "Nagarjun", type: "municipality" },
          { name: "Shankharapur", type: "municipality" },
          { name: "Tarakeshwar", type: "municipality" },
          { name: "Tokha", type: "municipality" },
        ],
      },
      {
        id: "28",
        name: "Kavrepalanchok",
        municipalities: [
          { name: "Banepa", type: "municipality" },
          { name: "Dhulikhel", type: "municipality" },
          { name: "Mandandeupur", type: "municipality" },
          { name: "Namobuddha", type: "municipality" },
          { name: "Panauti", type: "municipality" },
          { name: "Panchkhal", type: "municipality" },
          { name: "Bethanchowk", type: "rural-municipality" },
          { name: "Bhumlu", type: "rural-municipality" },
          { name: "Chaurideurali", type: "rural-municipality" },
          { name: "Khanikhola", type: "rural-municipality" },
          { name: "Mahabharat", type: "rural-municipality" },
          { name: "Roshi", type: "rural-municipality" },
          { name: "Temal", type: "rural-municipality" },
        ],
      },
      {
        id: "29",
        name: "Lalitpur",
        metropolises: [{ name: "Lalitpur", type: "metropolis" }],
        municipalities: [
          { name: "Godawari", type: "municipality" },
          { name: "Mahalaxmi", type: "municipality" },
        ],
        "rural-municipalities": [
          { name: "Bagmati", type: "rural-municipality" },
          { name: "Konjyosom", type: "rural-municipality" },
          { name: "Mahankal", type: "rural-municipality" },
        ],
      },
      {
        id: "30",
        name: "Makwanpur",
        municipalities: [
          { name: "Thaha", type: "municipality" },
          { name: "Hetauda", type: "sub-metropolis" },
          { name: "Bagmati", type: "rural-municipality" },
          { name: "Bakaiya", type: "rural-municipality" },
          { name: "Bhimphedi", type: "rural-municipality" },
          { name: "Indrasarowar", type: "rural-municipality" },
          { name: "Kailash", type: "rural-municipality" },
          { name: "Makawanpurgadhi", type: "rural-municipality" },
          { name: "Manahari", type: "rural-municipality" },
          { name: "Raksirang", type: "rural-municipality" },
        ],
      },
      {
        id: "31",
        name: "Nuwakot",
        municipalities: [
          { name: "Belkotgadhi", type: "municipality" },
          { name: "Bidur", type: "municipality" },
          { name: "Dupcheshwar", type: "rural-municipality" },
          { name: "Kakani", type: "rural-municipality" },
          { name: "Kispang", type: "rural-municipality" },
          { name: "Likhu", type: "rural-municipality" },
          { name: "Meghang", type: "rural-municipality" },
          { name: "Panchakanya", type: "rural-municipality" },
          { name: "Shivapuri", type: "rural-municipality" },
          { name: "Suryagadhi", type: "rural-municipality" },
          { name: "Tadi", type: "rural-municipality" },
          { name: "Tarkeshwar", type: "rural-municipality" },
        ],
      },
      {
        id: "32",
        name: "Ramechhap",
        municipalities: [
          { name: "Manthali", type: "municipality" },
          { name: "Ramechhap", type: "municipality" },
          { name: "Doramba", type: "rural-municipality" },
          { name: "Gokulganga", type: "rural-municipality" },
          { name: "Khadadevi", type: "rural-municipality" },
          { name: "Likhu", type: "rural-municipality" },
          { name: "Sunapati", type: "rural-municipality" },
          { name: "Umakunda", type: "rural-municipality" },
        ],
      },
      {
        id: "33",
        name: "Rasuwa",
        municipalities: [
          { name: "Gosaikunda", type: "rural-municipality" },
          { name: "Kalika", type: "rural-municipality" },
          { name: "Naukunda", type: "rural-municipality" },
          { name: "Parbatikunda", type: "rural-municipality" },
          { name: "Uttargaya", type: "rural-municipality" },
        ],
      },
      {
        id: "34",
        name: "Sindhuli",
        municipalities: [
          { name: "Dudhouli", type: "municipality" },
          { name: "Kamalamai", type: "municipality" },
          { name: "Ghanglekh", type: "rural-municipality" },
          { name: "Golanjor", type: "rural-municipality" },
          { name: "Hariharpurgadhi", type: "rural-municipality" },
          { name: "Marin", type: "rural-municipality" },
          { name: "Phikkal", type: "rural-municipality" },
          { name: "Sunkoshi", type: "rural-municipality" },
          { name: "Tinpatan", type: "rural-municipality" },
        ],
      },
      {
        id: "35",
        name: "Sindhupalchok",
        municipalities: [
          { name: "Barhabise", type: "municipality" },
          { name: "Chautara Sangachokgadhi", type: "municipality" },
          { name: "Melamchi", type: "municipality" },
          { name: "Balefi", type: "rural-municipality" },
          { name: "Bhotekoshi", type: "rural-municipality" },
          { name: "Helambu", type: "rural-municipality" },
          { name: "Indrawati", type: "rural-municipality" },
          { name: "Jugal", type: "rural-municipality" },
          { name: "Lisankhu Pakhar", type: "rural-municipality" },
          { name: "Panchpokhari Thangpal", type: "rural-municipality" },
          { name: "Sunkoshi", type: "rural-municipality" },
          { name: "Tripurasundari", type: "rural-municipality" },
        ],
      },
    ],
  },
  {
    id: "4",
    name: "Gandaki Pradesh",
    districts: [
      {
        id: "36",
        name: "Baglung",
        municipalities: [
          { id: "17", name: "Baglung", type: "municipality" },
          { id: "18", name: "Dhorpatan", type: "municipality" },
          { id: "19", name: "Galkot", type: "municipality" },
          { id: "20", name: "Jaimuni", type: "municipality" },
          { id: "21", name: "Badigad", type: "rural-municipality" },
          { id: "22", name: "Bareng", type: "rural-municipality" },
          { id: "23", name: "Kanthekhola", type: "rural-municipality" },
          { id: "24", name: "Nisikhola", type: "rural-municipality" },
          { id: "25", name: "Taman Khola", type: "rural-municipality" },
          { id: "26", name: "Tara Khola", type: "rural-municipality" },
        ],
      },
      {
        id: "37",
        name: "Gorkha",
        municipalities: [
          { name: "Gorkha", type: "municipality" },
          { name: "Palungtar", type: "municipality" },
          { name: "Aarughat", type: "rural-municipality" },
          { name: "Ajirkot", type: "rural-municipality" },
          { name: "Bhimsen", type: "rural-municipality" },
          { name: "Chum Nubri", type: "rural-municipality" },
          { name: "Dharche", type: "rural-municipality" },
          { name: "Gandaki", type: "rural-municipality" },
          { name: "Sahid Lakhan", type: "rural-municipality" },
          { name: "Siranchok", type: "rural-municipality" },
          { name: "Sulikot", type: "rural-municipality" },
        ],
      },
      {
        id: "38",
        name: "Kaski",
        metropolises: [{ name: "Pokhara Lekhnath", type: "metropolis" }],
        municipalities: [],
        "rural-municipalities": [
          { name: "Annapurna", type: "rural-municipality" },
          { name: "Machhapuchchhre", type: "rural-municipality" },
          { name: "Madi", type: "rural-municipality" },
          { name: "Rupa", type: "rural-municipality" },
        ],
      },
      {
        id: "39",
        name: "Lamjung",
        municipalities: [
          { name: "Besishahar", type: "municipality" },
          { name: "Madhyanepal", type: "municipality" },
          { name: "Rainas", type: "municipality" },
          { name: "Sundarbazar", type: "municipality" },
          { name: "Dordi", type: "rural-municipality" },
          { name: "Dudhpokhari", type: "rural-municipality" },
          { name: "Kwholasothar", type: "rural-municipality" },
          { name: "Marsyangdi", type: "rural-municipality" },
        ],
      },
      {
        id: "40",
        name: "Manang",
        municipalities: [
          { name: "Chame", type: "rural-municipality" },
          { name: "Narphu", type: "rural-municipality" },
          { name: "Nashong", type: "rural-municipality" },
          { name: "Neshyang", type: "rural-municipality" },
        ],
      },
      {
        id: "41",
        name: "Mustang",
        municipalities: [
          { name: "Barhagaun Muktikshetra", type: "rural-municipality" },
          { name: "Dalome", type: "rural-municipality" },
          { name: "Gharapjhong", type: "rural-municipality" },
          { name: "Lomanthang", type: "rural-municipality" },
          { name: "Thasang", type: "rural-municipality" },
        ],
      },
      {
        id: "42",
        name: "Myagdi",
        municipalities: [
          { name: "Beni", type: "municipality" },
          { name: "Annapurna", type: "rural-municipality" },
          { name: "Dhaulagiri", type: "rural-municipality" },
          { name: "Malika", type: "rural-municipality" },
          { name: "Mangala", type: "rural-municipality" },
          { name: "Raghuganga", type: "rural-municipality" },
        ],
      },
      {
        id: "43",
        name: "Nawalparasi (East)",
        municipalities: [
          { name: "Devchuli", type: "municipality" },
          { name: "Gaidakot", type: "municipality" },
          { name: "Kawaswoti", type: "municipality" },
          { name: "Madhyabindu", type: "municipality" },
          { name: "Binayee Triveni", type: "rural-municipality" },
          { name: "Bulingtar", type: "rural-municipality" },
          { name: "Bungdikali", type: "rural-municipality" },
          { name: "Hupsekot", type: "rural-municipality" },
        ],
      },
      {
        id: "44",
        name: "Nawalparasi (West)",
        municipalities: [
          { name: "Bardaghat", type: "municipality" },
          { name: "Ramgram", type: "municipality" },
          { name: "Sunwal", type: "municipality" },
          { name: "Palhi Nandan", type: "rural-municipality" },
          { name: "Pratappur", type: "rural-municipality" },
          { name: "Sarawal", type: "rural-municipality" },
          { name: "Susta", type: "rural-municipality" },
        ],
      },
      {
        id: "45",
        name: "Parbat",
        municipalities: [
          { name: "Kushma", type: "municipality" },
          { name: "Phalebas", type: "municipality" },
          { name: "Bihadi", type: "rural-municipality" },
          { name: "Jaljala", type: "rural-municipality" },
          { name: "Mahashila", type: "rural-municipality" },
          { name: "Modi", type: "rural-municipality" },
          { name: "Painyu", type: "rural-municipality" },
        ],
      },
      {
        id: "46",
        name: "Syangja",
        municipalities: [
          { name: "Bhirkot", type: "municipality" },
          { name: "Chapakot", type: "municipality" },
          { name: "Galyang", type: "municipality" },
          { name: "Putalibazar", type: "municipality" },
          { name: "Waling", type: "municipality" },
          { name: "Aandhikhola", type: "rural-municipality" },
          { name: "Arjunchaupari", type: "rural-municipality" },
          { name: "Biruwa", type: "rural-municipality" },
          { name: "Harinas", type: "rural-municipality" },
          { name: "Kaligandagi", type: "rural-municipality" },
          { name: "Phedikhola", type: "rural-municipality" },
        ],
      },
      {
        id: "47",
        name: "Tanahun",
        municipalities: [
          { name: "Bhanu", type: "municipality" },
          { name: "Bhimad", type: "municipality" },
          { name: "Byas", type: "municipality" },
          { name: "Shuklagandaki", type: "municipality" },
          { name: "Anbukhaireni", type: "rural-municipality" },
          { name: "Bandipur", type: "rural-municipality" },
          { name: "Devghat", type: "rural-municipality" },
          { name: "Ghiring", type: "rural-municipality" },
          { name: "Myagde", type: "rural-municipality" },
          { name: "Rhishing", type: "rural-municipality" },
        ],
      },
    ],
  },
  {
    id: "5",
    name: "Lumbini Pradesh",
    districts: [
      {
        id: "48",
        name: "Arghakhanchi",
        municipalities: [
          { id: "11", name: "Bhumekasthan", type: "municipality" },
          { id: "12", name: "Sandhikharka", type: "municipality" },
          { id: "13", name: "Sitganga", type: "municipality" },
          { id: "14", name: "Chhatradev", type: "rural-municipality" },
          { id: "15", name: "Malarani", type: "rural-municipality" },
          { id: "16", name: "Panini", type: "rural-municipality" },
        ],
      },
      {
        id: "49",
        name: "Banke",
        municipalities: [
          { id: "58", name: "Nepalganj", type: "sub-metropolis" },
          { id: "59", name: "Kohalpur", type: "municipality" },
          { id: "60", name: "Baijanath", type: "rural-municipality" },
          { id: "61", name: "Duduwa", type: "rural-municipality" },
          { id: "62", name: "Janki", type: "rural-municipality" },
          { id: "63", name: "Khajura", type: "rural-municipality" },
          { id: "64", name: "Narainapur", type: "rural-municipality" },
          { id: "65", name: "Rapti Sonari", type: "rural-municipality" },
        ],
      },
      {
        id: "50",
        name: "Bardiya",
        municipalities: [
          { id: "82", name: "Bansgadhi", type: "municipality" },
          { id: "83", name: "Barbardiya", type: "municipality" },
          { id: "84", name: "Gulariya", type: "municipality" },
          { id: "85", name: "Madhuwan", type: "municipality" },
          { id: "86", name: "Rajapur", type: "municipality" },
          { id: "87", name: "Thakurbaba", type: "municipality" },
          { id: "88", name: "Badhaiyatal", type: "rural-municipality" },
          { id: "89", name: "Geruwa", type: "rural-municipality" },
        ],
      },
      {
        id: "51",
        name: "Dang Deukhuri",
        municipalities: [
          { name: "Ghorahi", type: "sub-metropolis" },
          { name: "Tulsipur", type: "sub-metropolis" },
          { name: "Lamahi", type: "municipality" },
          { name: "Babai", type: "rural-municipality" },
          { name: "Banglachuli", type: "rural-municipality" },
          { name: "Dangisharan", type: "rural-municipality" },
          { name: "Gadhawa", type: "rural-municipality" },
          { name: "Rajpur", type: "rural-municipality" },
          { name: "Rapti", type: "rural-municipality" },
          { name: "Shantinagar", type: "rural-municipality" },
        ],
      },
      {
        id: "52",
        name: "Rukum (East)",
        municipalities: [
          { name: "Bhume", type: "rural-municipality" },
          { name: "Putha Uttarganga", type: "rural-municipality" },
          { name: "Sisne", type: "rural-municipality" },
        ],
      },
      {
        id: "53",
        name: "Gulmi",
        municipalities: [
          { name: "Musikot", type: "municipality" },
          { name: "Resunga", type: "municipality" },
          { name: "Chandrakot", type: "rural-municipality" },
          { name: "Chatrakot", type: "rural-municipality" },
          { name: "Dhurkot", type: "rural-municipality" },
          { name: "Gulmidarbar", type: "rural-municipality" },
          { name: "Isma", type: "rural-municipality" },
          { name: "Kaligandaki", type: "rural-municipality" },
          { name: "Madane", type: "rural-municipality" },
          { name: "Malika", type: "rural-municipality" },
          { name: "Ruru", type: "rural-municipality" },
          { name: "Satyawati", type: "rural-municipality" },
        ],
      },
      {
        id: "54",
        name: "Kapilvastu",
        municipalities: [
          { name: "Banganga", type: "municipality" },
          { name: "Buddhabhumi", type: "municipality" },
          { name: "Kapilbastu", type: "municipality" },
          { name: "Krishnanagar", type: "municipality" },
          { name: "Maharajgunj", type: "municipality" },
          { name: "Shivaraj", type: "municipality" },
          { name: "Bijayanagar", type: "rural-municipality" },
          { name: "Mayadevi", type: "rural-municipality" },
          { name: "Suddhodhan", type: "rural-municipality" },
          { name: "Yashodhara", type: "rural-municipality" },
        ],
      },
      {
        id: "55",
        name: "Palpa",
        municipalities: [
          { name: "Rampur", type: "municipality" },
          { name: "Tansen", type: "municipality" },
          { name: "Bagnaskali", type: "rural-municipality" },
          { name: "Mathagadhi", type: "rural-municipality" },
          { name: "Nisdi", type: "rural-municipality" },
          { name: "Purbakhola", type: "rural-municipality" },
          { name: "Rainadevi Chhahara", type: "rural-municipality" },
          { name: "Rambha", type: "rural-municipality" },
          { name: "Ribdikot", type: "rural-municipality" },
          { name: "Tinau", type: "rural-municipality" },
        ],
      },
      {
        id: "56",
        name: "Pyuthan",
        municipalities: [
          { name: "Pyuthan", type: "municipality" },
          { name: "Sworgadwary", type: "municipality" },
          { name: "Ayirabati", type: "rural-municipality" },
          { name: "Gaumukhi", type: "rural-municipality" },
          { name: "Jhimruk", type: "rural-municipality" },
          { name: "Mallarani", type: "rural-municipality" },
          { name: "Mandavi", type: "rural-municipality" },
          { name: "Naubahini", type: "rural-municipality" },
          { name: "Sarumarani", type: "rural-municipality" },
        ],
      },
      {
        id: "57",
        name: "Rolpa",
        municipalities: [
          { name: "Rolpa", type: "municipality" },
          { name: "Duikholi", type: "rural-municipality" },
          { name: "Lungri", type: "rural-municipality" },
          { name: "Madi", type: "rural-municipality" },
          { name: "Runtigadi", type: "rural-municipality" },
          { name: "Sukidaha", type: "rural-municipality" },
          { name: "Sunchhahari", type: "rural-municipality" },
          { name: "Suwarnabati", type: "rural-municipality" },
          { name: "Thawang", type: "rural-municipality" },
          { name: "Tribeni", type: "rural-municipality" },
        ],
      },
      {
        id: "58",
        name: "Rupandehi",
        municipalities: [
          { name: "Butwal", type: "sub-metropolis" },
          { name: "Devdaha", type: "municipality" },
          { name: "Lumbini Sanskritik", type: "municipality" },
          { name: "Sainamaina", type: "municipality" },
          { name: "Siddharthanagar", type: "municipality" },
          { name: "Tilottama", type: "municipality" },
          { name: "Gaidahawa", type: "rural-municipality" },
          { name: "Kanchan", type: "rural-municipality" },
          { name: "Kotahimai", type: "rural-municipality" },
          { name: "Marchawari", type: "rural-municipality" },
          { name: "Mayadevi", type: "rural-municipality" },
          { name: "Omsatiya", type: "rural-municipality" },
          { name: "Rohini", type: "rural-municipality" },
          { name: "Sammarimai", type: "rural-municipality" },
          { name: "Siyari", type: "rural-municipality" },
          { name: "Sudhdhodhan", type: "rural-municipality" },
        ],
      },
    ],
  },
  {
    id: "6",
    name: "Karnali Pradesh",
    districts: [
      {
        id: "59",
        name: "Dailekh",
        municipalities: [
          { name: "Aathabis", type: "municipality" },
          { name: "Chamunda Bindrasaini", type: "municipality" },
          { name: "Dullu", type: "municipality" },
          { name: "Narayan", type: "municipality" },
          { name: "Bhagawatimai", type: "rural-municipality" },
          { name: "Bhairabi", type: "rural-municipality" },
          { name: "Dungeshwor", type: "rural-municipality" },
          { name: "Gurans", type: "rural-municipality" },
          { name: "Mahabu", type: "rural-municipality" },
          { name: "Naumule", type: "rural-municipality" },
          { name: "Thantikandh", type: "rural-municipality" },
        ],
      },
      {
        id: "60",
        name: "Dolpa",
        municipalities: [
          { name: "Thuli Bheri", type: "municipality" },
          { name: "Tripurasundari", type: "municipality" },
          { name: "Chharka Tangsong", type: "rural-municipality" },
          { name: "Dolpo Buddha", type: "rural-municipality" },
          { name: "Jagadulla", type: "rural-municipality" },
          { name: "Kaike", type: "rural-municipality" },
          { name: "Mudkechula", type: "rural-municipality" },
          { name: "Shey Phoksundo", type: "rural-municipality" },
        ],
      },
      {
        id: "61",
        name: "Humla",
        municipalities: [
          { name: "Adanchuli", type: "rural-municipality" },
          { name: "Chankheli", type: "rural-municipality" },
          { name: "Kharpunath", type: "rural-municipality" },
          { name: "Namkha", type: "rural-municipality" },
          { name: "Sarkegad", type: "rural-municipality" },
          { name: "Simkot", type: "rural-municipality" },
          { name: "Tanjakot", type: "rural-municipality" },
        ],
      },
      {
        id: "62",
        name: "Jajarkot",
        municipalities: [
          { name: "Bheri", type: "municipality" },
          { name: "Chhedagad", type: "municipality" },
          { name: "Tribeni Nalagad", type: "municipality" },
          { name: "Barekot", type: "rural-municipality" },
          { name: "Junichande", type: "rural-municipality" },
          { name: "Kuse", type: "rural-municipality" },
          { name: "Shiwalaya", type: "rural-municipality" },
        ],
      },
      {
        id: "63",
        name: "Jumla",
        municipalities: [
          { name: "Chandannath", type: "municipality" },
          { name: "Guthichaur", type: "rural-municipality" },
          { name: "Hima", type: "rural-municipality" },
          { name: "Kanakasundari", type: "rural-municipality" },
          { name: "Patrasi", type: "rural-municipality" },
          { name: "Sinja", type: "rural-municipality" },
          { name: "Tatopani", type: "rural-municipality" },
          { name: "Tila", type: "rural-municipality" },
        ],
      },
      {
        id: "64",
        name: "Kalikot",
        municipalities: [
          { name: "Khandachakra", type: "municipality" },
          { name: "Raskot", type: "municipality" },
          { name: "Tilagufa", type: "municipality" },
          { name: "Kalika", type: "rural-municipality" },
          { name: "Mahawai", type: "rural-municipality" },
          { name: "Naraharinath", type: "rural-municipality" },
          { name: "Pachaljharana", type: "rural-municipality" },
          { name: "Palata", type: "rural-municipality" },
          { name: "Sanni Tribeni", type: "rural-municipality" },
        ],
      },
      {
        id: "65",
        name: "Mugu",
        municipalities: [
          { name: "Chhayanath Rara", type: "municipality" },
          { name: "Khatyad", type: "rural-municipality" },
          { name: "Mugum Karmarong", type: "rural-municipality" },
          { name: "Soru", type: "rural-municipality" },
        ],
      },
      {
        id: "66",
        name: "Salyan",
        municipalities: [
          { name: "Bagchaur", type: "municipality" },
          { name: "Bangad Kupinde", type: "municipality" },
          { name: "Sharada", type: "municipality" },
          { name: "Chhatreshwori", type: "rural-municipality" },
          { name: "Darma", type: "rural-municipality" },
          { name: "Dhorchaur", type: "rural-municipality" },
          { name: "Kalimati", type: "rural-municipality" },
          { name: "Kapurkot", type: "rural-municipality" },
          { name: "Kumakhmalika", type: "rural-municipality" },
          { name: "Tribeni", type: "rural-municipality" },
        ],
      },
      {
        id: "67",
        name: "Surkhet",
        municipalities: [
          { name: "Bheriganga", type: "municipality" },
          { name: "Birendranagar", type: "municipality" },
          { name: "Gurbhakot", type: "municipality" },
          { name: "Lekbesi", type: "municipality" },
          { name: "Panchpuri", type: "municipality" },
          { name: "Barahtal", type: "rural-municipality" },
          { name: "Chaukune", type: "rural-municipality" },
          { name: "Chingad", type: "rural-municipality" },
          { name: "Simta", type: "rural-municipality" },
        ],
      },
      {
        id: "68",
        name: "Rukum (West)",
        municipalities: [
          { name: "Aathbiskot", type: "municipality" },
          { name: "Chaurjahari", type: "municipality" },
          { name: "Musikot", type: "municipality" },
          { name: "Banfikot", type: "rural-municipality" },
          { name: "Sani Bheri", type: "rural-municipality" },
          { name: "Tribeni", type: "rural-municipality" },
        ],
      },
    ],
  },
  {
    id: "7",
    name: "Sudurpashchim Pradesh",
    districts: [
      {
        id: "69",
        name: "Achham",
        municipalities: [
          { id: "1", name: "Kamalbazar", type: "municipality" },
          { id: "2", name: "Mangalsen", type: "municipality" },
          { id: "3", name: "Panchadewal Binayak", type: "municipality" },
          { id: "4", name: "Sanphebagar", type: "municipality" },
          { id: "5", name: "Bannigadhi Jayagadh", type: "rural-municipality" },
          { id: "6", name: "Chaurpati", type: "rural-municipality" },
          { id: "7", name: "Dhakari", type: "rural-municipality" },
          { id: "8", name: "Mellekh", type: "rural-municipality" },
          { id: "9", name: "Ramaroshan", type: "rural-municipality" },
          { id: "10", name: "Turmakhad", type: "rural-municipality" },
        ],
      },
      {
        id: "70",
        name: "Baitadi",
        municipalities: [
          { id: "27", name: "Dasharathchanda", type: "municipality" },
          { id: "28", name: "Melauli", type: "municipality" },
          { id: "29", name: "Patan", type: "municipality" },
          { id: "30", name: "Purchaudi", type: "municipality" },
          { id: "31", name: "Dilasaini", type: "rural-municipality" },
          { id: "32", name: "Dogadakedar", type: "rural-municipality" },
          { id: "33", name: "Pancheshwar", type: "rural-municipality" },
          { id: "34", name: "Shivanath", type: "rural-municipality" },
          { id: "35", name: "Sigas", type: "rural-municipality" },
          { id: "36", name: "Surnaya", type: "rural-municipality" },
        ],
      },
      {
        id: "71",
        name: "Bajhang",
        municipalities: [
          { id: "37", name: "Bungal", type: "municipality" },
          { id: "38", name: "Jaya Prithivi", type: "municipality" },
          { id: "39", name: "Bithadchir", type: "rural-municipality" },
          { id: "40", name: "Chabispathivera", type: "rural-municipality" },
          { id: "41", name: "Durgathali", type: "rural-municipality" },
          { id: "42", name: "Kanda", type: "rural-municipality" },
          { id: "43", name: "Kedarseu", type: "rural-municipality" },
          { id: "44", name: "Khaptadchhanna", type: "rural-municipality" },
          { id: "45", name: "Masta", type: "rural-municipality" },
          { id: "46", name: "Surma", type: "rural-municipality" },
          { id: "47", name: "Talkot", type: "rural-municipality" },
          { id: "48", name: "Thalara", type: "rural-municipality" },
        ],
      },
      {
        id: "72",
        name: "Bajura",
        municipalities: [
          { id: "49", name: "Badimalika", type: "municipality" },
          { id: "50", name: "Budhiganga", type: "municipality" },
          { id: "51", name: "Budhinanda", type: "municipality" },
          { id: "52", name: "Tribeni", type: "municipality" },
          { id: "53", name: "Chhededaha", type: "rural-municipality" },
          { id: "54", name: "Gaumul", type: "rural-municipality" },
          { id: "55", name: "Himali", type: "rural-municipality" },
          { id: "56", name: "Pandav Gupha", type: "rural-municipality" },
          { id: "57", name: "Swami Kartik", type: "rural-municipality" },
        ],
      },
      {
        id: "73",
        name: "Dadeldhura",
        municipalities: [
          { name: "Amargadhi", type: "municipality" },
          { name: "Parashuram", type: "municipality" },
          { name: "Ajaymeru", type: "rural-municipality" },
          { name: "Alital", type: "rural-municipality" },
          { name: "Bhageshwar", type: "rural-municipality" },
          { name: "Ganayapdhura", type: "rural-municipality" },
          { name: "Nawadurga", type: "rural-municipality" },
        ],
      },
      {
        id: "74",
        name: "Darchula",
        municipalities: [
          { name: "Mahakali", type: "municipality" },
          { name: "Shailyashikhar", type: "municipality" },
          { name: "Apihimal", type: "rural-municipality" },
          { name: "Byas", type: "rural-municipality" },
          { name: "Dunhu", type: "rural-municipality" },
          { name: "Lekam", type: "rural-municipality" },
          { name: "Malikarjun", type: "rural-municipality" },
          { name: "Marma", type: "rural-municipality" },
          { name: "Naugad", type: "rural-municipality" },
        ],
      },
      {
        id: "75",
        name: "Doti",
        municipalities: [
          { name: "Dipayal Silgadhi", type: "municipality" },
          { name: "Shikhar", type: "municipality" },
          { name: "Adharsha", type: "rural-municipality" },
          { name: "Badikedar", type: "rural-municipality" },
          { name: "Bogtan", type: "rural-municipality" },
          { name: "Jorayal", type: "rural-municipality" },
          { name: "K I Singh", type: "rural-municipality" },
          { name: "Purbichauki", type: "rural-municipality" },
          { name: "Sayal", type: "rural-municipality" },
        ],
      },
      {
        id: "76",
        name: "Kailali",
        municipalities: [
          { name: "Dhangadhi", type: "sub-metropolis" },
          { name: "Bhajani", type: "municipality" },
          { name: "Gauriganga", type: "municipality" },
          { name: "Ghodaghodi", type: "municipality" },
          { name: "Godawari", type: "municipality" },
          { name: "Lamkichuha", type: "municipality" },
          { name: "Tikapur", type: "municipality" },
          { name: "Bardagoriya", type: "rural-municipality" },
          { name: "Chure", type: "rural-municipality" },
          { name: "Janaki", type: "rural-municipality" },
          { name: "Joshipur", type: "rural-municipality" },
          { name: "Kailari", type: "rural-municipality" },
          { name: "Mohanyal", type: "rural-municipality" },
        ],
      },
      {
        id: "77",
        name: "Kanchanpur",
        municipalities: [
          { name: "Bedkot", type: "municipality" },
          { name: "Belauri", type: "municipality" },
          { name: "Bhimdatta", type: "municipality" },
          { name: "Krishnapur", type: "municipality" },
          { name: "Mahakali", type: "municipality" },
          { name: "Punarbas", type: "municipality" },
          { name: "Suklaphanta", type: "municipality" },
          { name: "Beldandi", type: "rural-municipality" },
          { name: "Laljhandi", type: "rural-municipality" },
        ],
      },
    ],
  },
];
